### ISSUE TITLE
default styling overrides buttonClasses styles

### ISSUE THREAD

**Issue by aimanptz** [jodhman/react-eyedrop#19]
**Usage:**
![image](https://user-images.githubusercontent.com/36487126/80909592-147f7500-8d32-11ea-8cad-58dfac578422.png)

**Result:**
![image](https://user-images.githubusercontent.com/36487126/80909511-a9ce3980-8d31-11ea-9775-2b0edbf09b41.png)

Maybe I do something wrong but the custom styling is applied and overwritten with default values.

Thanks in advance!

**Comment by aimanptz** [comment]
Dived into src - the inline stylings are applied to the inner button, the only way to override is to use '!important' after every used in default styling prop. That might be a better option to use a css class instead, so the custom class will be more prioritized by default.

**Comment by jodhman** [comment]
Hey @aimanptz! Will have a proper look & fix for this in a few hours.
Appreciate you taking the time to report this. I'll let you know once the fix is out.

**Comment by jodhman** [comment]
Updated to version 4.1.2 where the default styles will applied to the CSS class.
Let me know if you run into any further trouble!
