### ISSUE TITLE
Allowing inline styling on the Eyedropper component?

### ISSUE THREAD

**Issue by gundamftw** [jodhman/react-eyedrop#4]
My app has a lot of Eyedropper buttons, and I want each button itself to change to the color of its dropped color. So I need the Eyedropper button itself to take inline styling, store the sampled color to a state, and then set the button's background-color to that state.

**Comment by jodhman** [comment]
Hey Gundam!
I hear you. Fortunately, this is already supported. In the README, find the documentation regarding properties `customComponent` and `passThrough`.

With these two properties combined, you'll be able to use your own button as component, and also give that component the eyedrop values onClick. Let me know if the documentation isn't clear enough around this, and I will happily provide an example. :-)

**Comment by gundamftw** [comment]
Hi I tried the `passThrough` property, it doesn't work. 

```javascript
const EyedropperButton = ({ onClick, droppedColors  }) => <button className="eyedropper-btn" id={droppedColors} style={{ backgroundColor: droppedColors }} onClick={onClick}></button>;

<EyeDropper     
    customComponent={EyedropperButton}
    passThrough={ data.high } />
```
The `data.high` is a string containing the color in hex, but when passed in, nothing shows up. I tried outputting it to the `id` value, but when inspected in chrome, the `id` property doesn't even show up.

**Comment by jodhman** [comment]
Ah! Yes. So, the way passThrough works:
Whatever string you pass in will be the property name for the color object. 

For instance, if `passThrough='colors'`, your custom component will receive a `colors` prop. Also note that the object given by passThrough has two props: one for hex code and one for rgb: make sure to use one of them. Console log it if in doubt. :-)

**Comment by gundamftw** [comment]
Okay I got what you're talking about:

````javascript
const EyedropperButton = ({ onClick, droppedColors  }) => <button className="eyedropper-btn" id={droppedColors} style={{ backgroundColor: droppedColors.hex }} onClick={onClick}></button>;

<EyeDropper     
    customComponent={EyedropperButton}
    passThrough='droppedColors' />
````
This will change the individual button color to the dropped color on button click. But what I'm looking for is storing the color to the database, and to have the buttons start with their stored color on page load. So I would need to do something like retrieve the color from the db on page load, save the data to state, and then have the button background color set to the state.

**Comment by jodhman** [comment]
Mmm... Sounds like you need more logic in your custom component then. :-)
This goes outside the scope of this Module, but if I were you, I would firstly figure out how to distinguish between the various buttons, perhaps by using IDs. You would then need to associate colors to IDs in your database. If the order matters, you would maybe even need a orderIndex property, depending on what database you're going to use.

Hope it helps! ^_^

**Comment by gundamftw** [comment]
I did do the logic, I have the array of colors in state displayed in the right order and I just need the Eyedropper button to show that color as well. At the end I would have to pass the state to the button, and that's what I thought the `passThrough` property would do. I mean how do I pass down values to the custom button?

**Comment by jodhman** [comment]
Yes, that's what `passThrough` is meant to handle. A way of giving your custom component the latest color values.
