### ISSUE TITLE
Eyedrop does not work on background image

### ISSUE THREAD

**Issue by sapirost** [jodhman/react-eyedrop#40]
When I'm trying to use eyedrop on an element with background-image I keep getting this value: 
`{rgb: 'rgb(255, 255, 255)', hex: '#ffffff'}`
Is it possible to inspect background-image? if not, is there any workaround to achieve the expected results?

Thanks in advance!

**Comment by jodhman** [comment]
Hey, @sapirost ! I'll have a look at it and get back to you. Give me a few moments.

**Comment by sapirost** [comment]
Thanks, @jodhman ! I really appreciate it
It is not urgent, I'll wait for a new version :)

**Comment by jodhman** [comment]
Sorry for the delay. Just pushed a new version `5.3.0`. It _should_ work with any HTML element. Let me know if it works for you, or if you run into any other issues!

Just bear in mind that images that are loaded from foreign domains without the Allow-Origin header will throw a CORS error.

**Comment by jodhman** [comment]
Closing this as time has passed & targeting HTML elements with a background property now functions.

Please don't hesitate to comment in this issue if you're still having issues.
