### ISSUE TITLE
backgroundImage check

### ISSUE THREAD

**Issue by iofjuupasli** [jodhman/react-eyedrop#50]
`window.getComputedStyle(element).backgroundImage` returns string `"none"`. So the check doesn't work as supposed

https://github.com/jodhman/react-eyedrop/blob/4a23ddec2a76ec8ef665c1f9525fc61a61938507/src/targetToCanvas/index.ts#L15

**Comment by jodhman** [comment]
Hello @iofjuupasli!
That's very true. Forgot to take the `"none"` value into account.
I'll push a fix and bump minor version. Will let you know as soon as it's done. 😄

**Comment by jodhman** [comment]
Hi again! This is now resolved in version `5.3.1`.
Thank you for submitting the issue here.
