### ISSUE TITLE
onPickStart, onPickEnd for hook

### ISSUE THREAD

**Issue by paulm17** [jodhman/react-eyedrop#55]
Thanks for taking the time to build this.  👍 

Would be awesome if you could include the events onPickStart and onPickEnd to the hook.

I have a use case where I'm using my own UI and want to know when the picker is activated or a color has been picked or feedback when cancelPickColor has been executed.

Thanks!

**Comment by jodhman** [comment]
Hello @paulm17! I'm glad you've found usage for it.
Version `5.4.0` comes with `onPickStart`, `onPickEnd` and `onPickCancel` for the hook.
Let me know if anything else comes up! :blush:

**Comment by paulm17** [comment]
@jodhman Sounds good.  The current version is 5.3.2, when will 5.4.0 be pushed to npm?

**Comment by jodhman** [comment]
My apologies. Please use `5.4.1`.
It should be pushed to NPM just now. If it doesn't show, it could be NPM's caching, give it some minutes :woman_dancing:

**Comment by paulm17** [comment]
Awesome!  Can confirm 5.4.1 and the new hook methods.  Many thanks!
